markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

gauges_id: 503c5af6613f5d0f19000027
google_analytics_id: UA-50755011-1

repository: https://github.com/pjkui/behaviac
help_url: https://github.com/pjkui/behaviac

collections:
  docs:
    output: true

name: behaviac â€¢ Simple, Game AI, offical websiste
description: Transform your plain text into static websites and blogs
url: http://pjkui.github.io/behaviac

gems:
  - jekyll-feed
